openmc-dev/data

convert_fendl.py, convert_tendl.py
Hi all,
Here is a pull request for some scripts that ease the downloading of FENDL and TENDL nuclear data libraries for your consideration.
The scripts are based on the existing OpenMC scripts for downloading JEFF and NNDC data. These two evaluations are of particular interest for fusion simulations as the ITER reactor requests FENDL data is used and the transmutation we expect in fusion reactors requires a library like TENDL with lots of isotopes when simulating burn-up.
Eventually I would like to add options for different releases, file formats (ENDF or ACE) and further nuclear data libraries such as CENDL and JENDL.
=> tendl and fendl download scripts added

generate_endf71.py
This script will generate a full ENDF/B-VII.1 library including neutron, photon, thermal scattering, and windowed multipole data. Because running NJOY for 400+ nuclides takes quite a bit of time, the processing is parallelized using the Python multiprocessing module.
This script can serve as a template for processing other full libraries.
=> Add script to generate full ENDF/B-VII.1 library using NJOY

download_all.sh, generate_cendl.py
Continuing the theme of including more nuclear data libraries.
This PR contains a new `generate_cendl.py` script that downloads and uses the openmc njoy functions to generate h5 files from the cendl endf files and makes it easy to use CENDL 3.1 with OpenMC.
There is one part of the script which fixes a couple of endf files as the CENDL 3.1 release contains a couple of files with non ASCII characters, as discussed in OpenMC issue #1177 
Also I spotted that the repo contains a `download_all.sh` script that was accidentally introduced last time, so this has been deleted. Sorry about that
=> Additon of CENDL nuclear data download script

convert_fendl.py
This PR fixes the convert_fendl.py script and relies on https://github.com/openmc-dev/openmc/pull/1277.
=> Use as_browser=True in convert_fendl.py

convert_jeff32.py
These changes allow separate temperature files from the JEFF 3.2 library to be downloaded.
For example the following command will download just 400K and 500K temperature ace files
python3 convert_jeff32.py -temperatures 400 500
Previously the script had to be edited manually when users wanted to download just a subsection of the 11 temperatures available.
I have also move the script from os.path to pathlib which saves a few lines of code in places
I have also done some generalising so that other releases of Jeff could perhaps be added
=> Jeff32 temperature control

generate_jendl.py
This is a small fix to correct an error that prevents the generate_jendl script downloading data.
`context=ssl._create_unverified_context()` was added to the call for download(url) to avoid the following error.
```
Traceback (most recent call last):
File "generate_jendl.py", line 81, in <module>
downloaded_file = download(url)
File "/home/jshim/openmc/openmc/_utils.py", line 34, in download
req = urlopen(page, **kwargs)
File "/usr/lib/python3.6/urllib/request.py", line 223, in urlopen
return opener.open(url, data, timeout)
File "/usr/lib/python3.6/urllib/request.py", line 526, in open
response = self._open(req, data)
File "/usr/lib/python3.6/urllib/request.py", line 544, in _open
'_open', req)
File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
result = func(*args)
File …
```
=> added ssl context to download

convert_nndc71.py
This is a first attempt at a general rewrite of the convert_nndc71.py script.
- The script now uses openmc.data.IncidentPhoton instead of running a subprocess call to openmc-ace-to-hdf5 which is a script that is not included in the data repository 
- The script now allows new arguments as first introduced in PR #8 
- The script also has a dictionary structure for the release details. This will allow us to ad future releases of nndc to the same script easily.
- pathlib is now being used instead of os.path
The script is not yet handling the S(a,b) cross sections and I could do with some pointers here and therefore this is a draft PR
Thanks all
=> general update of args, path instead of os.system, using incidentphoton

convert_nndc71.py
Small bug in the convert_nndc71.py scripy
When running the convert_nndc.py script the an error was noticed. This is looks like a typo as it was missing a comma
Thanks to @johnbillingsley96 for spotting this
=> added comma between items in list

convert_jeff33.py
This tiny PR makes some slight changes to the convert_jeff33.py script so that the ace files and h5 files are output to folders with the standard folder naming convention
Currently the ace files are extracted to a folder called ace which I though could be improved upon
=> Jeff 3.3 now using default ace folder like the other scripts

convert_fendl.py
This pull request contains changes related to issue #21 
I have included the following in the convert_fendl script:
- Photon data for FENDL-3.1a
- Photon data for FENDL-3.1d
- Neutron and Photon data for FENDL-3.0 
- Neutron and Photon data for FENDL-2.1
I also attempted to add FENDL-2.0 but faced problems because one of the energy laws required was not supported. This was discussed in #21 and an [issue](https://github.com/openmc-dev/openmc/issues/1487) was added to the main OpenMC repository 
I had some issues integrating FENDL-3.0 as K-39 ace file contained 'Inf' values within the data. OpenMC is unable to deal with this and cannot convert the file to HDF5. Although I looked into generating the file using the NJOY functionality built into OpenMC, it was decided that it was best to …
=> Add all releases and photon data to FENDL processing script

generate_cendl.py, generate_endf71.py, generate_jendl.py, utils.py
The script generate_endf71.py makes use of a multiprocessing pool to speed up the processing of endf files. This processing is done with NJOY and can take a while when there are a lot of files.
This PR is an attempt to bring this speed up to other scripts that generate h5 files from endf files with NJOY such as generate_jendl.py and gnerate_cendl.py.
This is achieved by moving two functions (process_neutron and process_thermal) from the generate_endf.py script into the utils.py script so that all the generate scripts can make use of them.
The multiprocessing pool is then implemented in the generate_jendl.py and gnerate_cendl.py scripts.
This PR was inspired by an PR in OpenMC which fixes a bug with parallel use of NJOY https://github.com/openmc-dev/openmc/pull/1522
I would recommend …
=> implemented pool processing for NJOY calls

generate_endf71.py, generate_jendl.py
Looks like we missed one detail in the refactor of generate_endf71.py. The generated neutron HDF5 files were not actually getting put in the `neutron/` output directory (and also wouldn't appear in the resulting cross_sections.xml file consequently.
=> Make sure neutron data goes to neutron/ directory

convert_lib80x.py, make_compton.py, make_stopping_powers.py
There were two scripts related to data generation that still lived in the main openmc repository. This PR simply moves them here and updates them to use pathlib consistently. Also, LANL just released an updated S(a,b) library for ENDF/B-VIII.0, so I've incorporated that into the convert_lib80x.py script.
=> Add scripts related to photon data

convert_jeff33.py, generate_jeff33.py
The original ACE data distributed by OECD/NEA for JEFF 3.3 only contained a single temperature. The current [distribution](https://www.oecd-nea.org/dbdata/jeff/jeff33/index.html) now contains neutron data at 293, 600, 900, 1200, 1500, and 1800 K.
=> Update JEFF 3.3 conversion script and add generation script

depletion/generate_endf71_chain_casl.py
This is a companion PR to openmc-dev/openmc#1679. Some of the same logic for calculating decay energy appeared in the CASL chain generation script. There is actually no error in the CASL (or ENDF/B-VII.1 chains) because none of the decay sublibrary files from ENDF/B-VII.1 are affected by the original bug (openmc-dev/openmc#1672).
=> Fix potential bug in decay energy calculation

README.md
Just adding a little table to the readme as a guide that shows what we have covered and the different options for downloading
Also I noticed the https://openmc.mcs.anl.gov/ website as two scripts for JEFF 3.3, just wondering if there is a difference
probably best to go here to see the rendered table https://github.com/openmc-dev/data/tree/adding_tables_to_readme
=> Adding tables to readme

convert_tendl_rand.py, sample_sandy.py
There is a small bug in `sample_sandy.py` (line 178).
Also allows the user to pass a `cross_sections.xml` file to which the random evaluations will be added.
Previously always `OPENMC_CROSS_SECTIONS` was imported. This is important because it is otherwise easy to mix random files from say TENDL with evaluations from another library.
=> Fixes small bug in sample_sandy.py and add small feature

README.md, generate_cendl.py
For zip file download, I've used [CNDC](http://www.nuclear.csdb.cn/cendl32.htm) web-link because OECD NEA didn't include it in their data bank but it's available from [IAEA-NDS](https://www-nds.iaea.org/public/download-endf/).
=> Add CENDL-3.2 Library

convert_fendl.py
It appears that the url we were using to download fendl 3.1d has moved.
I think this is because we were pointing to the latest fendl release url and now that version 3.2 has been released version 3.1d is no longer the latest.
So we can now grab that data from the archived urls and this PR is a small update to the url
I noticed this over on the CI for the new openmc-data-storage repository
https://github.com/openmc-data-storage/FENDL-3.1d/runs/2268201096?check_suite_focus=true
=> changed fendl 3.1d to the new url

depletion/chain_endfb71_pwr.xml, depletion/chain_endfb71_sfr.xml, depletion/generate_endf71_chain.py
A user [recently experienced problems](https://openmc.discourse.group/t/depletion-error-did-not-sample-any-reaction-for-nuclide-pb204/1362/3) trying to run a depletion simulation with the full ENDF/B-VII.1 depletion chain. It turns out the root cause of this problem was that the depletion chain results in Be7 getting added to depletable materials, and Be7 erroneously only has data up to ~8 MeV in ENDF/B-VII.1. Because the user's problem had neutrons > 10 MeV, this resulted in errors looking up cross sections. This PR manually removes Be7 from the ENDF/B-VII.1 depletion chains so that others don't run into this. Once it's merged, I'll update the data on openmc.org.
You'll also notice that an incorrect decay product from He5 was removed -- we had some logic in `Chain.from_endf` before that …
=> Remove Be7 from ENDF/B-VII.1 depletion chains

convert_tendl.py
TENDL 2021 just came out on 12/30/2021. This PR adds support to convert the ACE files that are provided on the [TENDL 2021 website](https://tendl.web.psi.ch/tendl_2021/tendl2021.html).
=> Support TENDL 2021 in convert_tendl.py script

README.md
I forgot to update the readme with the last to PR 
So this tiny PR adds the new versions of tendl and fendl to the readme table
=> added tendl2021 fendl2.2 to readme table

convert_nndc71.py, depletion/generate_endf71_chain.py, depletion/generate_endf71_chain_casl.py, depletion/generate_tendl_chain.py, generate_endf.py, generate_jeff33.py
I was just running the nice depletion/generate_endf71_chain.py script and got a 404 url not found error
so I went to the website and it looks like all the links have changed slightly.
I've been through and updated the links in a few places to get them working again
=> update failing links to new urls

generate_jeff33.py
@AnderGray noted that the generate_jeff33.py script fails on an MD5 hash check for JEFF33-n.tgz. I honestly have no idea what changed in this tarball since it was originally released, but I looked through it and all the files still have timestamps from 2018. So, in this PR I've just updated the MD5 hash so that the script can continue functioning :man_shrugging:
=> Update MD5 hash for JEFF 3.3 neutron sublibrary

LICENSE
This PR adds a license file which is the same as the OpenMC license
motivation
license files are needed by setup files when making packages and I'm [keen to make a package ](https://github.com/openmc-dev/data/issues/69)  :-)
=> added same lic as openmc

convert_nndc71.py, make_test_data.py
This PR moves the `openmc-make-test-data` script from the main openmc repo to this repo as `make_test_data.py`. I've made very little modification to the script other than fixing an import and the NNDC URLs. I ran the script to check that it goes to completion.
=> Add script to generate OpenMC data library used for testing purposes
